### ISSUE TITLE
Ops: get inode of a file when using `stat.full`

### ISSUE THREAD

**Issue by gbersac** [com-lihaoyi/Ammonite#1000]
Currently, this is how you get a file inode in ammonite:

```scala
import java.nio.file.Files
Files.getAttribute(pwd.toNIO, "unix:ino")
// => res6: Object = 11103024L
```
Wouldn't it be better if we could access it directly when calling `stat.full` (and avoiding the java api)?

**Comment by lihaoyi** [comment]
`ammonite-ops` is now EOLed in favor of os-lib, feel free to open the ticket there if you still need this
