### ISSUE TITLE
Symbol 'type scala.ScalaObject' is missing from the classpath

### ISSUE THREAD

**Issue by ingted** [com-lihaoyi/Ammonite#1012]
After import argonaut successfully,
```
import $ivy.{
            `io.argonaut::argonaut:6.2.3`
            } 

```
```
https://repo1.maven.org/maven2/io/argonaut/argonaut_2.13/6.2.3/argonaut_2.13-6.2.3.pom
  100.0% [##########] 1.7 KiB (1.9 KiB / s)
https://repo1.maven.org/maven2/io/argonaut/argonaut_2.13/6.2.3/argonaut_2.13-6.2.3-sources.jar
  100.0% [##########] 32.8 KiB (82.5 KiB / s)
https://repo1.maven.org/maven2/io/argonaut/argonaut_2.13/6.2.3/argonaut_2.13-6.2.3.jar
  100.0% [##########] 783.8 KiB (384.2 KiB / s)
```
and trying to import the package would fail.
```
argonaut._, Argonaut._ 
```
cmd4.sc:2: Symbol 'type scala.ScalaObject' is missing from the classpath.
This symbol is required by 'trait argonaut.ACursors'.
Make sure that type ScalaObject is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'ACursors.class' was compiled against an incompatible version of scala.
def $main() = { ammonite.repl.ReplBridge.value.Internal.combinePrints(
                ^
Compilation Failed
```

```

**Comment by lihaoyi** [comment]
seems to work now?

```scala
$ amm
Loading...
Welcome to the Ammonite Repl 2.4.1 (Scala 2.13.7 Java 11.0.7)
@ import $ivy.{
              `io.argonaut::argonaut:6.2.3`
              }

import $ivy.$

@ import argonaut._, Argonaut._
import argonaut._, Argonaut._
```
