### ISSUE TITLE
`toString` is a variable in REPL

### ISSUE THREAD

**Issue by weichuliu** [com-lihaoyi/Ammonite#1089]
Hi,

Today I realized `toString` in REPL is actually a String variable:

```
@ toString
res154: String = "cmd154"
@ toString
res155: String = "cmd155"
```

This caused confusing behavior like:

```
@ Seq(1, 2).map(toString)
res121: Seq[Char] = List('m', 'd')
```

(The code above should actually not compile, rather than giving an res.)

It `toString` intentionally exposed like this?

**Comment by lihaoyi** [comment]
Not intentional, but unlikely to be worth fixing
