### ISSUE TITLE
Instances of derived classes of case classes fail to render correctly

### ISSUE THREAD

**Issue by miguel-montes** [com-lihaoyi/Ammonite#1117]
When a class is derived from a case class or a trait is mixed with the base class, instances of them are rendered as instances of the base class:
Here is an example:

```scala
case class A(a: Int)

class DerivedA(a: Int, val b: Int) extends A(a){
  override def toString = s"DerivedA($a, $b)"
}
```
we get this

```
@ new DerivedA(1,2) 
res20: DerivedA = A(1)
```

instead of the expected

```
res20: DerivedA = DerivedA(1, 2)
```

**Comment by lihaoyi** [comment]
This is working as expected
