### ISSUE TITLE
ammonite-2.3.8-1 crash on startup with os.PathError$InvalidSegment

### ISSUE THREAD

**Issue by annappropriate** [com-lihaoyi/Ammonite#1129]
Ammonite began crashing after the most recent upgrade
```
$ amm
Loading...
Exception in thread "main" os.PathError$InvalidSegment: [] is not a valid path segment. OS-Lib does not allow empty path segments If you are dealing with path-strings coming from external sources, use the Path(...) or RelPath(...) constructor calls to convert them. 
        at os.BasePath$.fail$1(Path.scala:120)
        at os.BasePath$.checkSegment(Path.scala:137)
        at os.PathChunk$StringPathChunk.<init>(Path.scala:21)
        at os.PathChunk$.StringPathChunk(Path.scala:20)
        at ammonite.runtime.Storage$Folder.<init>(Storage.scala:189)
        at ammonite.MainRunner.initMain(Main.scala:452)
        at ammonite.MainRunner.watchLoop(Main.scala:396)
        at ammonite.MainRunner.runRepl(Main.scala:415)
        at ammonite.Main$.main0(Main.scala:321)
        at ammonite.Main$.main(Main.scala:270)
        at ammonite.Main.main(Main.scala)
$ pacman -Ss ammonite
community/ammonite 2.3.8-1 [installed]
    A cleanroom re-implementation of the Scala REPL from first principles.
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

I tried removing `~/.ammonite` just in case, but the result is the same.

Please let me know if I can provide more information.

**Comment by rolisv** [comment]
I'm on Arch Linux and getting this error too.
But I've noticed, that ammonite works, if I install it from prebuilt binaries according to instructions at https://ammonite.io/#Ammonite-REPL

```bash
$ (echo '#!/usr/bin/env sh' && curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.3.8/2.13-2.3.8) > ./amm && chmod +x ./amm
$ ./amm
Loading...
Welcome to the Ammonite Repl 2.3.8 (Scala 2.13.3 Java 15.0.1)
@
```
So this might be the distro packaging issue.

**Comment by annappropriate** [comment]
Right, vanilla ammonite works for me too.

**Comment by rolisv** [comment]
I've dug a little but deeper. I think the reason is that you cannot just build Ammonite from a source tarball, because the build expects the source to be in git repo.

When I build from cloned repo checked out at tag 2.3.8, it works fine. When I download and unpack source tarball https://github.com/lihaoyi/Ammonite/archive/2.3.8.tar.gz, it fails with:

```bash
$ mill -i 'amm[2.13.3].assembly'
Compiling /home/ro/workspace/github/Ammonite-2.3.8/build.sc
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
os.SubprocessException: CommandResult 128

  os.proc.call(ProcessOps.scala:85)
  ammonite.$file.build.$init$(build.sc:11)
  ammonite.$file.build$.<clinit>(build.sc:40)
```
Ammonite PKGBUILD (https://github.com/archlinux/svntogit-community/blob/packages/ammonite/trunk/PKGBUILD) runs a number of `sed` commands to eliminate calls to `git` from `build.sc`, but that does not seem to completely solve the problem.

I wonder if there is some official support for building Ammonite from a source tarball.

**Comment by DrPhil** [comment]
Since this seems to be a problem in the packaging (if it works to build from source), it should be reported in the Arch repo and not here. I opened a bug report there: https://bugs.archlinux.org/task/69241
