### ISSUE TITLE
Autocomplete suggested invalid Scala identifiers

### ISSUE THREAD

**Issue by harpocrates** [com-lihaoyi/Ammonite#1142]
Despite the bug description, this is actually a tiny edge case (maybe not worth worrying about at all?).

The JVM spec allows for method or field names that are otherwise invalid in Scala or Java, such as `foo-bar`. Only [`. ; [ /` are disallowed](https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-4.html#jvms-4.2.2). Scala accommodates a whole bunch more symbols by expanding them out into `$<escapename>`, the idea being that those names are still usable from Java. For example: Scala's `foo-bar` actually turns into `foo$minusbar`.

However, if we load a class with a name that Scala would normally escape, there is no way to refer to that name directly.
This leads to somewhat confusing interactions where Ammonite tab-completion suggests the unescaped name, without hinting at the fact that this name can't actually be used from Scala:

```
Welcome to the Ammonite Repl 2.2.0 (Scala 2.13.3 Java 1.8.0_241)
@ res.
as-br_table-value-index      memory
@ res.`as-br_table-value-index`
cmd0.sc:1: value as-br_table-value-index is not a member of me.alec.BranchTable
val res0 = res.`as-br_table-value-index`
               ^
Compilation Failed

@ res.getClass.getMethod("as-br_table-value-index")
res1: java.lang.reflect.Method = public final int me.alec.BranchTable.as-br_table-value-index()
```

I think that when using tab-complete, Ammonite should not suggest names that cannot be written in Scala.

**Comment by scalway** [comment]
I guess this is not a ammonite thing at all. If methods cannot be accessed from scala then we should not care...
It is rather rare case and it does not break anything.

**Comment by lihaoyi** [comment]
Yeah gonna call this a wontfix I think
