### ISSUE TITLE
selenium new version java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;

### ISSUE THREAD

**Issue by zheh12** [com-lihaoyi/Ammonite#1149]
For the selenium version 3.14.0, it can't work with exception
java.lang.NoSuchMethodError: com.google.common.util.concurrent.SimpleTimeLimiter.create(Ljava/util/concurrent/ExecutorService;)Lcom/google/common/util/concurrent/SimpleTimeLimiter;

And I found the root cause is amm add bsp4j as its dependence and bsp4j has guava 21.0 as its dependence.
But selenium needs guava 25.0-jre, but I don't have a good idea to fix it. Anyone can help?

**Comment by zhongl** [comment]
Run `amm --thin` should workaround it.
