### ISSUE TITLE
Ammonite REPL url broken

### ISSUE THREAD

**Issue by RajivKulkarni707** [com-lihaoyi/Ammonite#1166]
Hello,

I am trying to download and install the scala REPL.

However, the url mentioned in README file seems to be broken.

**Ammonite-REPL, the improved Scala REPL**

Please let me know alternative way to install the REPL.

Thanks
Rajiv

**Comment by RajivKulkarni707** [comment]
Sorry, forgot to mention that I am currently working with Windows 10 environment.

Please point me to alternative steps to install the REPL on Windows.
 
Thanks
Rajiv

**Comment by Glavo** [comment]
Download it: https://github.com/com-lihaoyi/Ammonite/releases/download/2.3.8/2.13-2.3.8
This is actually a jar file, you just need to execute `java -jar 2.13-2.3.8` to start it. Of course, you can also write a bat script to start it more easily.
