### ISSUE TITLE
Ammonite does not seem to search added Maven repository

### ISSUE THREAD

**Issue by nchammas** [com-lihaoyi/Ammonite#1178]
I've added a Maven repository as shown in [the docs](https://ammonite.io/#import$ivy):

```scala
import coursierapi.{Credentials, MavenRepository}

interp.repositories() ++= Seq(
  MavenRepository
    .of("https://nexus.corp.com/content/repositories/releases")
    .withCredentials(Credentials.of("user", "pass"))
)
```

However, when I try to import something that itself depends on some libraries published to this private Maven repository, Ammonite does not seem to search there:

```
import $ivy.`com.private::core:1.1.0-SNAPSHOT`
---
Failed to resolve ivy dependencies:Error downloading com.private:java-common:4.0.15
  not found: /Users/nchammas/.ivy2/local/com.private/java-common/4.0.15/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/private/java-common/4.0.15/java-common-4.0.15.pom
```

Even though I can see the added repo if I inspect `interp.repositories()`:

```scala
interp.repositories().foreach(println)
---
ApiRepo(IvyRepository(Pattern(List(Const(file:/Users/nchammas/.ivy2/local/), Var(organisation), Const(/), Var(module), Const(/), Opt(List(Const(scala_), Var(scalaVersion), Const(/))), Opt(List(Const(sbt_), Var(sbtVersion), Const(/))), Var(revision), Const(/), Var(type), Const(s/), Var(artifact), Opt(List(Const(-), Var(classifier))), Const(.), Var(ext))), None, None, true, true, true, true, None, true))
ApiRepo(MavenRepository(https://repo1.maven.org/maven2, None, None, true, true))
MavenRepository(https://nexus.corp.com/content/repositories/releases, Credentials(user, ****))
```

Why isn't Ammonite searching the added `nexus.corp.com` Maven repository? Also, what is the difference between `ApiRepo(MavenRepository(...))` and `MavenRepository(...)` in the printed output?

I'm running Ammonite Repl 2.3.8 (Scala 2.12.12 Java 1.8.0_282).

**Comment by ckipp01** [comment]
Not sure if this will help at all, but I have this working at work for a private maven repository, and the only difference is we use `interp.repositories.bind(List(...))`.

**Comment by nchammas** [comment]
Hmm, I think I might be doing something very basic incorrectly. It seems that `$ivy.` directives are evaluated before anything else, even if the `import $ivy.` line occurs after my changes to `interp.repositories()`. So Ammonite doesn't see the updated repositories in time to use them for the import.

So I need to somehow run the repository modifications before the `$ivy.` stuff runs. Any idea how I might do that? I'm trying to run a full `.sc` script all at once, so I can't just manually paste the repo changes into an active Ammonite REPL before then running the Ivy import.

**Comment by ckipp01** [comment]
Jumping back in here after I realize why this was working for me. I'm not sure if this is an option for you or not @nchammas but I just hit on this again and from playing around a bit more, it seems that if I have the `interp.repositories() ++=` in the same file as my script, it won't work. However, if I have another file where I add them, and then import that file into my script via `import $file.Access.sc, Access._` and then do the actual import there, it all works.

**Comment by lihaoyi** [comment]
Yeah the issue here is you need to put the `interp.repositories()` call either in a separate script, or in an earlier pat of the script separated by a `@` from the main body containing the `import $ivy`. This is confusing, but unfortunately is the status quo for now
