### ISSUE TITLE
Could not fetch ammonite-repl-api_3.0.0

### ISSUE THREAD

**Issue by i10416** [com-lihaoyi/Ammonite#1188]
It failed when I tried to fetch ammonite-repl-api_3.0.0 from VS Code by adding magic comments at the top of a file.
example.sc
``` scala
// Ammonite 2.4.0
// scala 3.0.0

```
Is ammonite-repl-api for 3.0.0  yet to be released?

Logs
```
not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite-repl-api_3.0.0/2.4.0/ammonite-repl-api_3.0.0-2.4.0.pom
```

Is this related https://github.com/com-lihaoyi/Ammonite/pull/1187?

**Comment by ckipp01** [comment]
Hi @ItoYo16u when using Metals, behind the scenes we are actually using [ammonite-runner](https://github.com/alexarchambault/ammonite-runner), which allows to set the versions like you do via comments. That's not actually part of Ammonite. There were a lot of breaking changes in Ammonite 2.4.0, so before this will actually work, this would need to be taken care of: https://github.com/alexarchambault/ammonite-runner/issues/118

**Comment by ItoYo16u** [comment]
Thank you for inform that!
I will take a look at ammonite runner.
