### ISSUE TITLE
@arg(doc = ...) on main function does not print documentation

### ISSUE THREAD

**Issue by imRentable** [com-lihaoyi/Ammonite#1213]
Hi,

I am trying to document a main function as described [here](https://github.com/com-lihaoyi/Ammonite/tree/master/amm/src/test/resources/mains/MultiMainDoc.sc#L0-L20). However, only the documentation of the function arguments is printed as usage hint when I call the script with insufficient arguments. I expected to see the documentation of the function signature itself as well. Or did I misunderstand something?

I am using v2.4.0.

**Comment by lolgab** [comment]
This works correctly on Ammonite `3.0.0-M0-59-cdeaa580` in both Scala 2 Scala 3.
Closing the issue.
