### ISSUE TITLE
Unclear ammonite install location for shebang

### ISSUE THREAD

**Issue by nrktkt** [com-lihaoyi/Ammonite#1216]
In [the documentation](http://ammonite.io/#FromBash) the suggested shebang is `#!/usr/bin/env amm`.
However in the [install documentation](http://ammonite.io/#ScalaScripts), the suggested install command puts `amm` at `/usr/local/bin/amm`
```
$ sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.4.0/2.13-2.4.0) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm
```

It should probably be one or the other, but which is preferred? Should the install command create a symlink to compensate for previous inconsistency?

**Comment by alexarchambault** [comment]
Yeah, this shouldn't be a problem, @nrktkt.
