### ISSUE TITLE
Can I use Scala3 in ammonite?

### ISSUE THREAD

**Issue by Runky-op** [com-lihaoyi/Ammonite#1235]
![3H)16FD$FZET88~OI)0C}KK](https://user-images.githubusercontent.com/52552971/145400518-115e0854-5352-4a27-92b0-226af08b06aa.png)
I wanna use scala3, is there a way?

**Comment by sake92** [comment]
Yes, you need to download a `3.0-2.4.151.1` version from here: https://github.com/com-lihaoyi/Ammonite/releases
