### ISSUE TITLE
Scala 3 extension methods - autocompletion?

### ISSUE THREAD

**Issue by Quafadas** [com-lihaoyi/Ammonite#1238]
For me with Ammonite 2.5.0, "normal" methods are tab-completable, but extension methods are not, in scala 3.0.2. 

I guess this is be a feature request for that?

**Comment by Quafadas** [comment]
I think , that it is also not possible to "define" extension methods, based on my experiments.

**Comment by Quafadas** [comment]
Looks like it now works...

**Comment by mpollmeier** [comment]
Do you happen to remember if you tested a few edge cases? See https://github.com/com-lihaoyi/Ammonite/issues/1297 for some - maybe these worked in a previous version?
