### ISSUE TITLE
ammonite-shell not published for version 2.5.0

### ISSUE THREAD

**Issue by mrdziuban** [com-lihaoyi/Ammonite#1239]
Thanks for all your hard work on ammonite! I'm trying to upgrade to 2.5.0 and found that when loading the shell, I get a resolution error for `ammonite-shell_2.13.7_2.5.0`, which seems to not be published for version 2.5.0: https://mvnrepository.com/artifact/com.lihaoyi/ammonite-shell. Would publishing it be pretty straightforward?

**Comment by SethTisue** [comment]
sounds like #1227?

**Comment by SethTisue** [comment]
I got confused for a minute between 1.5.0 and 2.5.0. The latter removes Ammonite Shell as per #1227, but I see now that you're talking about 1.5.0 which is an old version.

Is there a reason you need to upgrade to that specific old version (from December 2018)?

**Comment by mrdziuban** [comment]
Oh shoot sorry, I did mean 2.5.0, but I should have looked more closely at the release notes! My old `predef.sc` (which was pulled from [this `example-predef.sc`](https://github.com/com-lihaoyi/Ammonite/pull/1227/files#diff-b9bdc6115e79b1bf1a6fc27f07a028dc93315c938a2d493c092bdfe158249163) that's been removed) and `predefScript.cs` still refer to `ammonite-shell` -- do I still need the predef files for any reason?

Other than that, it looks like the only other thing I need to do to upgrade is replace uses of `%` and `%%` (from `ammonite-ops`) with `os.proc` -- does that seem right?

**Comment by SethTisue** [comment]
(I don't know, hopefully someone else will answer)

**Comment by mrdziuban** [comment]
Everything seems to be working properly without the predef scripts, and all of my scripts are compiling with `os-lib` equivalents of `ammonite-ops`, so closing this issue. Thanks for the help @SethTisue!
