### ISSUE TITLE
How to download version 2.5.2

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [com-lihaoyi/Ammonite#1249]
The documentation still references old 2.5.1 version.
I've tried unsuccesfully:
```
sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.5.2/3.1-2.5.2) > /usr/local/bin/amm3 && chmod +x /usr/local/bin/amm3' && amm3
```

**Comment by jvr-ks** [comment]
Take a look at:
[https://mvnrepository.com/artifact/com.lihaoyi/ammonite](https://mvnrepository.com/artifact/com.lihaoyi/ammonite)
The latest version available today (2022/02/01) is 2.5.1-7-cd989427

**Comment by alexarchambault** [comment]
I might have messed with the release… Trying to run its CI jobs again.

**Comment by DavidPerezIngeniero** [comment]
Maybe I was confused by reading in the github page that latest is 2.5.2 and in the changelog of the main pages states that 2.5.2 is the latest one, compatible with Scala 3.0 and 3.1.

**Comment by alexarchambault** [comment]
New attempt (the Ammonite release workflow looks really different than the ones of my projects…)

**Comment by alexarchambault** [comment]
Ok, the artifacts should be there.

**Comment by deusaquilus** [comment]
This link works for me!
```
sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.5.2/3.1-2.5.2) > /usr/local/bin/amm3 && chmod +x /usr/local/bin/amm3' && amm3
```
Thanks @DavidPerezIngeniero and @alexarchambault!
