### ISSUE TITLE
MatchError on macro expansion

### ISSUE THREAD

**Issue by worekleszczy** [com-lihaoyi/Ammonite#1258]
Hey, first of all I want to say that I really enjoy using ammonite :)

## Problem

I've been getting a following error lately:

```
cmd2.sc:8: exception during macro expansion: 
scala.MatchError: [x]fs2.Pure[x] (of class scala.reflect.internal.Types$PolyType)
	at pprint.TPrintLowPri$.typePrintImplRec0(TPrintImpl.scala:151)
	at pprint.TPrintLowPri$.typePrintImplRec(TPrintImpl.scala:32)
	at pprint.TPrintLowPri$.$anonfun$typePrintImplRec0$7(TPrintImpl.scala:103)
	at scala.collection.immutable.List.map(List.scala:246)
	at pprint.TPrintLowPri$.added$2(TPrintImpl.scala:103)
	at pprint.TPrintLowPri$.printArgs$1(TPrintImpl.scala:106)
	at pprint.TPrintLowPri$.typePrintImplRec0(TPrintImpl.scala:200)
	at pprint.TPrintLowPri$.typePrintImplRec(TPrintImpl.scala:32)
	at pprint.TPrintLowPri$.typePrintImpl(TPrintImpl.scala:21)

          .print(res2, "res2", _root_.scala.None)
                ^
Compilation Failed
```

## Reproduction steps

* launch ammonite `cs launch ammonite --scala 2.13.8` 
* run following code:
```
import $ivy.`co.fs2:fs2-core_2.13:3.2.4`, fs2._

Stream.emits(Seq(1,2,3))
```
## Machine spec

* `Ammonite 2.5.2`
* `Scala 2.13.8` / `Scala 2.13.6` 
*  `Java 17.0.2` (but I've tried version 11 too)
* Apple M1 Pro Chip - this might be important, as I don't recall getting this error on other machines

**Comment by worekleszczy** [comment]
Encountered it again and found out this make it compile:
```
Stream.emits[fs2.Pure, String](Seq("a"))
```
It seems like the problem is type bound `F[x] >: fs2.Pure[x]` in **fs2**

**Comment by alexarchambault** [comment]
It seems it's been fixed in recent Ammonite versions. I can't reproduce that with `2.5.5` (while I can with `2.5.2`).

**Comment by worekleszczy** [comment]
@alexarchambault You're right - in `2.5.5` the problem is gone 🙃 I always launch `amm` with `cs launch ammonite --scala 2.13.8` so by default it starts `2.5.2` version and I assumed it's always the newest one. Closing this then.

BTW I'm not sure if this is ammonite problem or coursier, but running `cs launch ammonite --scala 2.13.9` fails with:
```
Resolution error: Error downloading com.lihaoyi:ammonite_2.13.9:latest.release
```
but this:
```
cs launch com.lihaoyi:ammonite_2.13.9:2.5.5 -M ammonite.Main
```
works fine. 🤷🏼‍♂️

**Comment by alexarchambault** [comment]
> BTW I'm not sure if this is ammonite problem or coursier,

Yeah, there are issues in the automatic Scala suffix logic, in coursier…
