### ISSUE TITLE
[Scala3] Unable to define extension methods in REPL

### ISSUE THREAD

**Issue by tanishiking** [com-lihaoyi/Ammonite#1281]
```
❯ scala-cli repl --scala 3.1.3 --ammonite
Loading...
Welcome to the Ammonite Repl 2.5.4-11-4f5bf2aa (Scala 3.1.3 Java 17.0.3)
@ extension (foo: Int)
    def bar = foo

-- [E006] Not Found Error: cmd0.sc:1:11 ----------------------------------------
1 |val res0 = extension (foo: Int)
  |           ^^^^^^^^^
  |           Not found: extension
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: cmd0.sc:1:22 ----------------------------------------
1 |val res0 = extension (foo: Int)
  |                      ^^^
  |                      Not found: foo
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: cmd0.sc:2:12 ----------------------------------------
2 |  def bar = foo
  |            ^^^
  |            Not found: foo
  |
  | longer explanation available when compiling with `-explain`
Compilation Failed
```

It would be nice if we can define extension methods as normal REPL can do that

```
❯ scala-cli repl --scala 3.1.3
Welcome to Scala 3.1.3 (17.0.3, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> extension (foo: Int)
     |   def bar = foo
     |
def bar(foo: Int): Int

scala> 1.bar
val res0: Int = 1
```

---

It looks like the problem is, the preprocessor for Scala3 doesn't expect to have the `extension keyword` here https://github.com/com-lihaoyi/Ammonite/blob/dc4c47bc5f08aec6466fb133cbee66a8184e353c/amm/compiler/src/main/scala-3/ammonite/compiler/Preprocessor.scala#L256-L258 right?

I'm new to the Ammonite codebase, but I'm willing to contribute to this :)

**Comment by alexarchambault** [comment]
> It looks like the problem is, the preprocessor for Scala3 doesn't expect to have the `extension keyword` here , right?
> I'm new to the Ammonite codebase, but I'm willing to contribute to this :)

@tanishiking I think that's the right part of the codebase that needs tweaking. Feel free to fix it, yes!
