### ISSUE TITLE
Publish final Ammonite 2.5.5 for Scala version 3.2.1?

### ISSUE THREAD

**Issue by swaldman** [com-lihaoyi/Ammonite#1314]
Hi!

With a Scala 3.2.1 build, `./mill untemplatedocs.repl` fails for me:
```
1 targets failed
untemplatedocs.resolvedAmmoniteReplIvyDeps 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:ammonite_3.2.1:2.5.5 
	not found: /Users/swaldman/.ivy2/local/com.lihaoyi/ammonite_3.2.1/2.5.5/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite_3.2.1/2.5.5/ammonite_3.2.1-2.5.5.pom
```

It works with a 3.2.0 build. A quick jump to `https://repo1.maven.org/maven2/` confirms that, for [`3.2.0`](https://repo1.maven.org/maven2/com/lihaoyi/ammonite_3.2.0/) there exists a clean `2.5.5` dir, while for [`3.2.1`](https://repo1.maven.org/maven2/com/lihaoyi/ammonite_3.2.1/) only a not-so-clean (nightly?) `2.5.5-17-df243e14` dir exists.

Would it be possible to publish the final version of Ammonite 2.5.5 for Scala 3.2.1?

Many thanks!

**Comment by lefou** [comment]
It's not very likely to expect a `2.5.5` release for Scala `3.2.1`, as out automated release tooling isn't built for that case. But we gladly cut a new release once we got support for Scala `3.2.1` in. PRs welcome.

**Comment by swaldman** [comment]
I thought Ammonite already [did support 3.2.1](https://github.com/com-lihaoyi/Ammonite/pull/1311). What PRs would you welcome? I'd be glad to help if I can.

**Comment by lefou** [comment]
Oh, I forgot about that when writing the answer. That makes it easier. We just need to write a changelog and pull the trigger. Let me do that tomorrow.

**Comment by swaldman** [comment]
Great. Thank you!

If there is anything that I can do to help, please let me know!

**Comment by lefou** [comment]
I just tagged `2.5.6`. Release needs some time though.

**Comment by swaldman** [comment]
Thanks a ton.
