### ISSUE TITLE
import scala.sys.process.* does not work after ammonite version 2.5.3

### ISSUE THREAD

**Issue by dmassart** [com-lihaoyi/Ammonite#1326]
Until version 2.5.3 of ammonite it was possible to use import scala.sys.process.* to run a command line instruction from the script.
This is broken in the following versions.

**Comment by lefou** [comment]
Can you provide a reproducer, as it's not clear what you mean exactly. I just discovered, that the documentation still contains some traces of the now removed `ammonite.ops` API, which might look similar to `scala.sys.process.*` due to the heavily used `!`. You should use [os-lib](https://github.com/com-lihaoyi/os-lib) instead.

**Comment by dmassart** [comment]
Yes, sorry I should have provided an example.

import scala.language.postfixOps
import scala.sys.process.*
s"wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/pubmed23n1244.xml.gz"!!

If I put these 3 lines in a file, running it with ammonite 2.5.3 (Scala 3.1.2 Java 19) or earlier does the job (i.e., downloads the file) while newer versions - e.g., ammonite 2.5.6 (Scala 3.0.2 Java 19) raises a java.lang.AssertionError 

scala.MatchError: class dotty.tools.dotc.reporting.Diagnostic at download.sc:[290..299..315]: type ParserForMethods is not a member of mainargs - did you mean mainargs.ParserForMethods? (of class dotty.tools.dotc.reporting.Diagnostic)
	at dotty.tools.dotc.reporting.MessageRendering.diagnosticLevel(MessageRendering.scala:180)

**Comment by dmassart** [comment]
just tried 

import $ivy.`com.lihaoyi::os-lib:0.9.0`
os.proc("curl", "ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/pubmed23n1244.xml.gz", "--output", "test.gz").spawn(stderr = os.Inherit)

Interestingly, I get similar results: ammonite 2.5.3 downloads the file while ammonite 2.5.6 raises a java.lang.AssertionError

**Comment by lefou** [comment]
I think Ammonite 2.5.6 does no longer support Scala 3.0.x. Please try with at least Scala 3.1.1. The CI runs of PR https://github.com/com-lihaoyi/Ammonite/pull/1316 suggest it's the lowest Scala 3 version that works. (In your example above, you tested Ammonite 2.5.3 with Scala 3.1.2 but Ammonite 2.5.6 with Scala 3.0.2.)

Also, you don't need to manually import os-lib. It's already included in Ammonite.

**Comment by dmassart** [comment]
Just tried running the script with https://github.com/com-lihaoyi/Ammonite/releases/download/3.0.0-M0/3.2-3.0.0-M0 and it works.
Thanks for the help.
