### ISSUE TITLE
Publish for Scala 2.12.18 and 2.13.11, please?

### ISSUE THREAD

**Issue by SethTisue** [com-lihaoyi/Ammonite#1349]
2.12.18 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/9

2.13.11 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/11

**Comment by LuciferYang** [comment]
@alexarchambault Is there a plan for the Ammonite to release a new version? Thanks ~

**Comment by 3XC1T3D** [comment]
Is there any ETA when a new Amonite Release will be release due to this issue?

**Comment by lefou** [comment]
Ammonite 2.5.9 release is out.
