### ISSUE TITLE
Latest CI fails while releasing amm for Scala 2.13

### ISSUE THREAD

**Issue by lwronski** [com-lihaoyi/Ammonite#1378]
It looks like that the latest [CI](https://github.com/com-lihaoyi/Ammonite/actions/runs/6175939129/job/16763827399) in `main` run failed during the release of amm for Scala `2.13.12`. Notably, latest amm version for Scala `2.13.12` is not available on [Maven](https://mvnrepository.com/artifact/com.lihaoyi/ammonite). 

**Expected behaviour**
I would expect releasing amm version which support Scala version `2.13.12` and `3.3.1`.

**Comment by lefou** [comment]
Version `3.0.0-M0-53-084f7f4e` should now be published completely.

**Comment by LuciferYang** [comment]
Will there be a corresponding version for 2.x released? Thanks ~

**Comment by lefou** [comment]
> Will there be a corresponding version for 2.x released? Thanks ~

It already is: `2.5.9-2-7633e640`

**Comment by LuciferYang** [comment]
Thank you very much ~
