### ISSUE TITLE
Publish for Scala 3.3.2, 3.3.3 & 3.4.0

### ISSUE THREAD

**Issue by Gedochao** [com-lihaoyi/Ammonite#1425]
The artifacts are available on Maven already
- [x] 3.3.2: https://index.scala-lang.org/lampepfl/dotty/artifacts/scala3-compiler/3.3.2
- [x] 3.3.3: https://index.scala-lang.org/lampepfl/dotty/artifacts/scala3-compiler/3.3.3
- [ ] 3.4.0: https://index.scala-lang.org/lampepfl/dotty/artifacts/scala3-compiler/3.4.0

## Context
3.4.0 is blocked by:
- https://github.com/com-lihaoyi/Ammonite/issues/1395
  - related to https://github.com/lampepfl/dotty/issues/19702

My attempt:
- https://github.com/com-lihaoyi/Ammonite/pull/1394

**Comment by sideeffffect** [comment]
This PR has been merged, so this issue can be closed
 * https://github.com/com-lihaoyi/Ammonite/pull/1503
