### ISSUE TITLE
import $ivy ERROR

### ISSUE THREAD

**Issue by StruggleYang** [com-lihaoyi/Ammonite#1486]
```
> amm
Loading...
Welcome to the Ammonite Repl 2.5.0 (Scala 2.13.7 Java 1.8.0_191)
@ import $ivy.`com.google.guava:guava:18.0`, com.google.common.collect._
Failed to resolve ivy dependencies:Error downloading com.google.guava:guava:18.0
  not found: /home/xxx/.ivy2/local/com.google.guava/guava/18.0/ivys/ivy.xml
  checksum format error: /home/xxx/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom.sha1
```

**Comment by lefou** [comment]
Looks like an coursier issue to me. We saw these kind of issue often in Mill until we implemented a handler to detect and retry. I thought those were fix meanwhile (e.g. https://github.com/coursier/coursier/pull/2591), but am not sure. A coursier update might help.

See also

**Comment by StruggleYang** [comment]
> Looks like an coursier issue to me. We saw these kind of issue often in Mill until we implemented a handler to detect and retry. I thought those were fix meanwhile (e.g. https://github.com/coursier/coursier/pull/2591), but am not sure. 
> 
> 
> 
> You should use a more recent version of Ammonite. `2.5.0` is not the newest. Either `2.5.11` or `3.0.0-M1` should contain newer versions of coursier.
> 
> 

Thanks, lefou, I finally found out that it was my network problem, thanks for your reply, I will upgrade it to the new version in the next few days, thanks again
