### ISSUE TITLE
no 3.3-3.0.0-M2 release artifact? 

### ISSUE THREAD

**Issue by raboof** [com-lihaoyi/Ammonite#1498]
There was a `3.3-3.0.0-M1` in https://github.com/com-lihaoyi/Ammonite/releases/tag/3.0.0-M1 but there is no `3.3-3.0.0-M2` in https://github.com/com-lihaoyi/Ammonite/releases/tag/3.0.0-M2 - is that intentional?

**Comment by lefou** [comment]
Thanks for letting us know. Due to https://github.com/com-lihaoyi/Ammonite/issues/1491, I had to manually fix this release and forgot to renamed that file.
