### ISSUE TITLE
Publish artifact for 2.5.x / Scala 2.13.14

### ISSUE THREAD

**Issue by kschuetz** [com-lihaoyi/Ammonite#1501]
Since 3.0 hasn't been officially released yet, would it be possible to get a release of 2.5.x that supports Scala 2.13.14?

Thanks.

**Comment by lefou** [comment]
We could cut a `3.0.0` instead. We entered a milestone-release phase for `3.0` to be open to binary incompatible changes. But it looks like none more are planned, so we can also settle for `3.0`.

**Comment by lefou** [comment]
In the meantime, using `3.0.0-M2` is perfectly fine from a maturity perspective.

**Comment by lihaoyi** [comment]
Released in Ammonite 3.0.0

**Comment by kschuetz** [comment]
Appreciate it. Thanks!
