### ISSUE TITLE
Add support for Scala 3.4.3 & 3.5.0

### ISSUE THREAD

**Issue by Gedochao** [com-lihaoyi/Ammonite#1533]
- [ ] Scala 3.4.3 https://github.com/scala/scala3/issues/21385
- [x] Scala 3.5.0 https://github.com/scala/scala3/issues/21368

**Comment by beyondpie** [comment]
@Gedochao 
When I try ammonite under scala 3.5.0, I got the error,

> 
> Welcome to the Ammonite Repl 3.0.0-M2-15-9bed9700 (Scala 3.4.2 Java 22.0.1-internal)
> @  error while loading scala,
> TASTy file scala/NamedTupleDecomposition.tasty could not be read, failing with:
>   Forward incompatible TASTy file has version 28.5, produced by Scala 3.5.0-bin-nonbootstrapped,
>   expected stable TASTy from 28.0 to 28.4.
>   To read this TASTy file, use a Scala 3.5.0 compiler or newer.
>   Please refer to the documentation for information on TASTy versioning:
>   https://docs.scala-lang.org/scala3/reference/language-versions/binary-compatibility.html

Is this related with the issue you list here? 

Thanks!
Songpeng
