### ISSUE TITLE
Ammonite Paths do not handle symlinks

### ISSUE THREAD

**Issue by tbu-** [com-lihaoyi/Ammonite#187]
In the presentation about Ammonite I saw that relative paths get normalized in a way that doesn't correspond to what Linux does.

Consider `/bin` linking to `/usr/bin`. Then the path `/bin/..` would be normalized to `/` by Ammonite when it actually refers to `/usr` in Linux.

**Comment by lihaoyi** [comment]
I'm not seeing this behavior on any of my machines, OSX or Ubuntu. In both cases the behavior of `ls` matches that of Ammonite

<img width="829" alt="screenshot 2015-08-21 09 21 03" src="https://cloud.githubusercontent.com/assets/934140/9413307/fb619a3a-47e5-11e5-8c92-497e392e1911.png">

**Comment by tbu-** [comment]
Sorry, what I said only works if `/bin` actually is a symlink to `/usr/bin`, which doesn't appear to be the case on your system.

Here's a minimal test case that should work on your system:

    $ mkdir -p parent/target/
    $ ln -s parent/target/ link
    $ ls link/../
    target

**Comment by lihaoyi** [comment]
Hmmm ok. In general tools for dealing with symlinks are lacking.

**Comment by tomjridge** [comment]
Broken symlinks also cause problems for ammonite

**Comment by lihaoyi** [comment]
Superseded by the move to OS-Lib, which generally has flags to control handling of symlinks
