### ISSUE TITLE
Resolve `$file` and `$exec` imports relative to `wd` and not `cwd`

### ISSUE THREAD

**Issue by yakticus** [com-lihaoyi/Ammonite#447]
Resolve `$file` and `$exec` imports relative to `wd` and not `cwd`

helpful tips from @lihaoyi :

> https://github.com/lihaoyi/Ammonite/blob/master/amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala#L89
> 
> which for scripts is the path to the script itself, but for imports from the REPL are a synthetic thing
> defined 
> 
> https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala/ammonite/runtime/Interpreter.scala#L214
> 
> which uses the wd currently hardcoded when instantiating each Interpreter...
> 
> there are multiple things called wd here :grinning: the thing internal to Interpreter, and the thingy 
> 
> internal to ammonite.shell
> 
> First step would be to soft-code it and make it a var or Ref, then expose an Ref in ReplAPI where the wd can be changed from the REPL, then make the ammonite.shell code make use of that Ref to read/write the wd
> 
> and last step would be to handle the funniness and make sure sure the same absolute-file-on-disk doesn't end up being multiple logical-packages inside the Scala classpath; i.e. if you cd! after importing some script and import the same script again, it doesn't import the script as a whole new package
> 
> we already do that to import $file so different scripts can import different import $file.foo.bars or import $file.baz.foo.bar and get the same java package, since $file imports are relative to the script directory

**Comment by yakticus** [comment]
some comments from @lihaoyi (not all addressed in this issue, but good context):
```
currently the wd variable is defined in the ammonite-shell package, which is a third-party thing, though there is also a wd inside ammRuntime Interpreter.scala that is used to resolve import $file.* calls

the correct thing to do would be to expose the Interpreter's `wd` as `interp.wd: Ref[Path]` in the REPL and make it settable, and then have the ammonite-shell cd! function update it
```

**Comment by lihaoyi** [comment]
This is now moot since ammonite-ops has been EOLed
