### ISSUE TITLE
Document the r string interpolator

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [com-lihaoyi/Ammonite#467]
I'd like to have some documentation about the very useful r interpolator.

Example use in the REPL:

``` scala
"hola" match {
    case r"h$j" => j
    case _ => "nothing"
  } 
```

But I don't know how to use it in my own projects.  I find it very useful.

**Comment by DavidPerezIngeniero** [comment]
Finally, I've found it in:
https://github.com/lihaoyi/Ammonite/blob/4919dcc2d2046e1083cb984d2e7c80ba99dfde29/ops/src/main/scala/ammonite/ops/Extensions.scala

**Comment by lihaoyi** [comment]
Probably moot now that ammonite-ops is EOLed
