### ISSUE TITLE
Make path to current script available within script

### ISSUE THREAD

**Issue by trungfinity** [com-lihaoyi/Ammonite#646]
Hi,

Is there any alternative to `BASH_SOURCE[0]` currently be supported in Ammonite? I think it's pretty convenient in order to run Ammonite scripts instead of Bash scripts.

**Comment by lihaoyi** [comment]
What is `BASH_SOURCE[0]`?

**Comment by ngthanhtrung** [comment]
It's the location of the script being executed by bash. For now I workaround by creating a bash file wrapper:

`fetch.sh`:
```sh
#!/bin/bash

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

/usr/bin/env amm "${BASE_DIR}/fetch.sc" "$@" --path "${BASE_DIR}"
```

`fetch.sc`:
```scala
#!/usr/bin/env amm

import ammonite.ops._
import scalaj.http._

@main
def blah(path: Path) = {
  val theFile = path/up/"relative"/"path"/"to"/"the"/"script"
  // Do something with `theFile`
}
```

**Comment by ngthanhtrung** [comment]
I think one of the use case for Ammonite is writing script files which involve complex operations (HTTP operations, JSON parsing, etc.). Those operations are hard to implement in bash without using any external dependency so I usually write them in Python. I'm giving Ammonite a try for those tasks now.

**Comment by ngthanhtrung** [comment]
For that use case, I find myself using `BASH_SOURCE[0]` so many times. I think people with the same use case would agree with me. Ammonite codebase is quite strange to me at the first glance but I'm willing to help on this issue.

**Comment by lihaoyi** [comment]
@ngthanhtrung ok I understand what you want, and it makes sense to me that such a thing would be useful. I updated the title of this issue to reflect my current understanding.

**Comment by ngthanhtrung** [comment]
That's right.

**Comment by lihaoyi** [comment]
FWIW this is not as simple as adding another builtin to `InterpAPI`, since it needs to be a different value lexically in each script that may be imported, and must remain that value even if e.g. the script finishes executing the first time but then someone else calls a function defined in it. We'd need to statically define a different value into every script file's wrapper to make this work

**Comment by Grogs** [comment]
You could avoid the wrapper script by using a multiline shebang.

For example, this script would pass the path to the script as the first argument to the script:

```
#!/bin/sh
  exec /usr/local/bin/amm -s "$0" "$0" "$@"
!#

@main
def main(args: String*) {
    println(args)
}
```

However, it will print the relative path. From there, if you're using Linux, you could use `readlink -f` to get the full path.

**Comment by Krever** [comment]
> FWIW this is not as simple as adding another builtin to InterpAPI, since it needs to be a different value lexically in each script that may be imported, and must remain that value even if e.g. the script finishes executing the first time but then someone else calls a function defined in it.
>
>We'd need to statically define a different value into every script file's wrapper to make this work, or use a macro that expands during compilation to the file path of that script

@lihaoyi could you elaborate a bit? I'm considering working on this and would like to know some more details.

I think we need to decide if we want to support this feature in `import $file` or only in `amm script.sc`. My original thought was only about the latter. And in such case, it should be enough to add something to `InterpAPI` or even better add a separate bridge just for this feature(I think `InterpApi` is used in different places that will not have a meaningful implementation).

**Comment by TJSomething** [comment]
I needed this for an embedded REPL, so I passed to following argument to `Main` for a workaround:

```scala
ammonite.Main(
// ...
      scriptCodeWrapper =
        new Preprocessor.CodeWrapper
        {
          override def apply(
            code: String,
            source: Util.CodeSource,
            imports: Imports,
            printCode: String,
            indexedWrapperName: Name,
            extraCode: String,
          ): (String, String, Int) = {
            val (topWrapper, bottomWrapper, userCodeNestingLevel) =
              Preprocessor.CodeWrapper(
                code = code,
                source = source,
                imports = imports,
                printCode = printCode,
                indexedWrapperName = indexedWrapperName,
                extraCode = extraCode,
              )
            val mungedTop = source.path match {
              case Some(file) =>
                s"""$topWrapper
                   |private val __FILE__ = "${file.toNIO.toAbsolutePath}"
                   |
                 """.stripMargin
              case None => topWrapper
            }
            (mungedTop, bottomWrapper, userCodeNestingLevel)
          }
        }
      ,
// ...
```

**Comment by Esardes** [comment]
only missing feature I can think of to get rid of my Makefiles for good
