### ISSUE TITLE
Scrolling on Website is Unusably Slow

### ISSUE THREAD

**Issue by jamesward** [com-lihaoyi/Ammonite#751]
On the latest Chrome, scrolling up/down on http://ammonite.io/ takes forever.  Here is the profiling output:
![screen shot 2018-02-14 at 12 53 41 pm](https://user-images.githubusercontent.com/65043/36224885-1ed7796e-1186-11e8-8bde-4b08983fdd1a.png)

**Comment by AndyMoreland** [comment]
workaround is to block javascript on the page -- makes it nice and speedy.

**Comment by sake92** [comment]
Overall site load says: 
- 12.3 MB, most of it are images, gifs...  
- 14 seconds to load

Some stuff from audit tab:
- first meaningful paint: after 5.7 seconds
- does not use HTTPS

All in all, very poor performance. 😟   
We should split it to multiple pages. It would be more user-friendly and easier to read.

My suggestion is to use a static site generator like Jekyll, Docusaurus ([scalafmt docs](https://github.com/scalameta/scalafmt/pull/1199) is migrating to it) or even my [Hepek generator](https://sake92.github.io/hepek/) (IMHO better than to use a custom script like Mill [does](https://github.com/lihaoyi/mill/blob/master/docs/build.sc)).  
I'm willing to spend time on this.

**Comment by sake92** [comment]
After #1170 now it takes 3 seconds to load, and around 2MB on initial load. 🎉
