### ISSUE TITLE
Scrips: Seperate 'predefCode' and 'on completion open up a REPL'

### ISSUE THREAD

**Issue by Tamriel** [com-lihaoyi/Ammonite#827]
I want to run a script from an SBT project and preload own code: `ammonite.Main.main(Array("--predef-code", "val a = 2", new File("hello.sc").getAbsolutePath))`
Sadly, the command `predef-code` is bundled with 'This will run the script as normal, but on completion open up a REPL which has all the values defined in that script imported and ready to use.'
I think these two options should be separated, e.g. with the addition of the option `--open-repl-on-completion`.

**Comment by lihaoyi** [comment]
Seems to be fixed now?


```scala
$ cat foo.sc
println(a)

$ amm --version
Ammonite REPL & Script-Runner, 2.4.1

$ amm --predef-code "val a = 1" foo.sc
1
```
