### ISSUE TITLE
timeout cannot be used with some commands

### ISSUE THREAD

**Issue by ADayn** [com-lihaoyi/Ammonite#952]
When running the `timeout` command with `%` or `%%`, some sub-commands block forever. If you're not familiar with it, `timeout 45 command` runs `command` and fails if it runs for more than 45 seconds. An example:
```
amm -c "import ammonite.ops._
import ammonite.ops.ImplicitWd._
%('timeout,  \"60\", \"sbt\", \"about\")"
```
Will block until it times out. Similarly, if the following is run:
```
amm -c "import ammonite.ops._
import ammonite.ops.ImplicitWd._
%('timeout,  \"60\", \"python\")"
```
then the following is printed before timeout:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
But it doesn't print the prompt (usually ">>>") and won't take input.

If it's relevant, my use case here is to timeout `sbt test` for an assignment grading script.

Both of these work fine in other shells.

**Comment by ADayn** [comment]
I should mention that this isn't an issue with all commands, for example running `%('timeout, "60", "echo", "hi")` works fine.

**Comment by lihaoyi** [comment]
Probably moot now that ammonite-ops is EOLed
