### ISSUE TITLE
Add command to query "build" information of scripts 

### ISSUE THREAD

**Issue by Baccata** [com-lihaoyi/Ammonite#977]
I've already started working on this, but opening a ticket to track possible discussions and point to a branch when I'm happy

The goal is to provide a command for ammonite to dump build-related information to stdout, in json, so that metals can pick it up and provide editor support for ammonite scripts (and hopefully mill, while we're at it). 

The current limitation is that accessing this information means entering a compile/run loop. Obviously, we do not want to unknowingly run scripts whilst we're editing them, as it could have unfortunate consequences (drop table much ?) 

I'm gonna try and deliver a prototype branch as soon as possible to act as a support for design discussions. 

See relevant metals topic : https://github.com/scalameta/metals-feature-requests/issues/17

**Comment by lihaoyi** [comment]
We have some basic metals support now, so I think this can be closed
